# Generated by Django 4.2.17 on 2024-12-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_remove_event_description_remove_event_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='date',
        ),
    ]
