# Generated by Django 6.0.1 on 2026-01-24 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_remove_event_title_event_is_available_event_tasks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_report', models.DateField()),
                ('come_all_weather', models.BooleanField(default=False)),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('group_leader_name', models.CharField(max_length=100)),
                ('group_leader_address', models.TextField()),
                ('group_leader_email', models.EmailField(max_length=254)),
                ('group_leader_phone', models.IntegerField()),
                ('nbr_adult', models.PositiveIntegerField()),
                ('nbr_child', models.PositiveIntegerField()),
                ('nbr_wheelchair', models.PositiveIntegerField()),
                ('price_adult', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_child', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meal_included', models.BooleanField(default=False)),
                ('meal_price_adult', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meal_price_child', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_total', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('meal_comments', models.TextField(blank=True, null=True)),
                ('last_modifired', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.bookingtype')),
            ],
        ),
    ]
