# Generated by Django 6.0.1 on 2026-01-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_bookingtype_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.bookingtype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_report',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nbr_wheelchair',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
