# Generated by Django 6.0.1 on 2026-01-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_booking_booking_type_alter_booking_date_report_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='last_modifired',
            new_name='last_author',
        ),
    ]
