# Generated by Django 6.0.1 on 2026-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_rename_last_modifired_booking_last_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group_leader_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
