# Generated by Django 6.0.1 on 2026-02-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_alter_booking_group_leader_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('add_availability', 'Add personal availability'), ('assign_task', 'Assign a Task')]},
        ),
    ]
