# Generated by Django 6.0.1 on 2026-02-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('bookings_view', 'View bookings'), ('bookings_manager', 'Manage bookings')]},
        ),
        migrations.AlterModelOptions(
            name='bookingtype',
            options={'permissions': [('bookings_admin', 'Admin bookings')]},
        ),
    ]
