# Generated by Django 6.0.1 on 2026-02-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_alter_booking_options_alter_bookingtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingtype',
            options={},
        ),
    ]
