# Generated by Django 6.0.1 on 2026-02-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_alter_bookingtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('assign_task', 'Assign a Task')]},
        ),
    ]
