# Generated by Django 6.0.1 on 2026-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_replaceable',
            field=models.BooleanField(default=False),
        ),
    ]
