# Generated by Django 6.1.1 on 2026-09-16 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_event_is_replaceable'),
        ('tasks', '0007_alter_authorizations_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_author',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_event_per_day_for_user'),
        ),
        migrations.DeleteModel(
            name='BookingType',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
