# Generated by Django 5.2.1 on 2025-07-26 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_authorizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorizations',
            unique_together={('user', 'task')},
        ),
    ]
