# Generated by Django 6.0.1 on 2026-02-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('Trainer', 'Trainer rights')]},
        ),
        migrations.AlterModelOptions(
            name='commenttype',
            options={'permissions': [('admin', 'Admin rights on tasks')]},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'permissions': [('admin', 'Admin rights on tasks')]},
        ),
    ]
