# Generated by Django 6.0.1 on 2026-02-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_comment_options_alter_commenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizations',
            options={'permissions': [('Trainer', 'Trainer rights')]},
        ),
        migrations.AlterModelOptions(
            name='commenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={},
        ),
    ]
